# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxExample
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Starscream'
	pod 'SwiftLint'

end
