# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftStudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxExample
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'OAuthSwift'
  pod 'RxDataSources'
  pod 'RxKeyboard'
  pod 'RxAlamofire'

end
